### ISSUE TITLE
Design : Home Page

### ISSUE THREAD

**Issue by Low4ey** [Low4ey/CodeRoyale#14]

**Comment by jals413** [comment]
This should be marquee without see deals button

![image](https://github.com/Low4ey/Oj_Front_end/assets/63969102/3cedba54-bea1-43f1-a3c5-fd6e8ed36b4f)

**Comment by jals413** [comment]
![image](https://github.com/Low4ey/Oj_Front_end/assets/63969102/1f507cd8-1899-4457-a232-2db3b53a2819)

**Comment by jals413** [comment]
@karikay18  please finish this asap
